# -*- coding: utf-8 -*-
{
    'name': "purchase_report",
    'version': "13.2.1",
    'category': 'Purchase, Purchase Request',
    'depends': ['base', 'purchase', 'purchase_stock', 'stock'],
    'website': 'https://docs.google.com/document/d/1uI5U9cjFtqly-3zb1xDGYpkuz_5hHy3a/edit',
    'author': "Sambath Vatana, E Sokmean",
    'summary': "Report of Purchase Order/RFQ/Purchase Request/Picking List",
    'data': [
        'views/purchase_report.xml',
        'report/purchaseorder_footer.xml',
        'report/purchaseorder_header.xml',
        'report/purchase_order_report_template.xml',
        'report/purchaserequest_footer.xml',
        'report/purchaserequest_header.xml',
        'report/purchase_request_report_template.xml',
        'report/rfq_footer.xml',
        'report/rfq_header.xml',
        'report/request_for_quotation_report.xml',
        'report/report_header_footer.xml',
        'report/a2a_report.xml',
        'report/vkiriom_report.xml',
        'views/a2a_report_view.xml',
        'views/vkirirom_report_view.xml',
    ],
    'installable': True,
}
